/** メニュー名から絵文字アイコンを推定する共通ユーティリティ */
export function guessMenuIcon(name: string): string {
  if (/生ビール|ビール/.test(name))               return '🍺'
  if (/チューハイ|ハイボール|酎ハイ/.test(name))  return '🥂'
  if (/日本酒|梅酒/.test(name))                   return '🍶'
  if (/コーラ|ジュース|ソフト/.test(name))         return '🥤'
  if (/お茶|ウーロン/.test(name))                 return '🍵'
  if (/焼き鳥|やきとり/.test(name))               return '🍢'
  if (/から揚げ|唐揚げ|竜田|手羽/.test(name))      return '🍗'
  if (/チキン南蛮/.test(name))                    return '🍗'
  if (/弁当/.test(name))                          return '🍱'
  if (/丼/.test(name))                            return '🍚'
  if (/ポテト|フライ/.test(name))                 return '🍟'
  if (/おにぎり/.test(name))                     return '🍙'
  if (/枝豆/.test(name))                          return '🫛'
  if (/キムチ/.test(name))                       return '🌶'
  if (/コロッケ/.test(name))                     return '🥔'
  if (/もつ煮/.test(name))                       return '🍲'
  if (/サラダ/.test(name))                       return '🥗'
  if (/玉子|たまご/.test(name))                  return '🥚'
  if (/焼きそば/.test(name))                     return '🍜'
  if (/焼きおにぎり/.test(name))                 return '🍙'
  return '🍽'
}
